import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import {
   MatCardModule,
   MatButtonModule,
   MatToolbarModule,
   MatIconModule,
   MatBadgeModule,
   MatSidenavModule,
   MatListModule,
   MatGridListModule,
   MatFormFieldModule,
   MatInputModule,
   MatSelectModule,
   MatDatepickerModule,
   MatNativeDateModule,
   MatChipsModule,
   MatTableModule,
   MatPaginatorModule,
   MatSnackBarModule,
   MatSlideToggleModule,
   MatProgressBarModule,
   MatSortModule,
   MatButtonToggleModule,
   MatTabsModule,
   MatExpansionModule,
} from '@angular/material';

@NgModule({
   imports: [
      CommonModule,
      MatButtonModule,
      MatToolbarModule,
      MatIconModule,
      MatSidenavModule,
      MatBadgeModule,
      MatListModule,
      MatGridListModule,
      MatFormFieldModule,
      MatInputModule,
      MatSelectModule,
      MatDatepickerModule,
      MatNativeDateModule,
      MatChipsModule,
      MatTableModule,
      MatPaginatorModule,
      MatCardModule,
      MatSnackBarModule,
      MatSlideToggleModule,
      MatProgressBarModule,
      MatSortModule,
      MatButtonToggleModule,
      MatTabsModule,
      MatExpansionModule
   ],
   exports: [
      MatButtonModule,
      MatToolbarModule,
      MatIconModule,
      MatSidenavModule,
      MatBadgeModule,
      MatListModule,
      MatGridListModule,
      MatInputModule,
      MatFormFieldModule,
      MatSelectModule,
      MatDatepickerModule,
      MatChipsModule,
      MatTableModule,
      MatPaginatorModule,
      MatCardModule,
      MatSnackBarModule,
      MatSlideToggleModule,
      MatProgressBarModule,
      MatButtonToggleModule,
      MatTabsModule,
      MatExpansionModule
   ],
   providers: [
      MatDatepickerModule,
   ]
})

export class AngularMaterialModule { }